// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yppffgwsepvcrqdvegwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwcGZmZ3dzZXB2Y3JxZHZlZ3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDY2MDgsImV4cCI6MjA2Mzg4MjYwOH0.eUIpR2fitzQ6IYWg1n8ntscnz2H82ptCcMZw6Qnme3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);